saas/config/routes.rb
Saas::Application.routes.draw do

  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/contact"
  get "static_pages/about"

  match '/home' => 'static_pages#home'
  match '/help' => 'static_pages#help'
  match '/about' => 'static_pages#about'
  match '/contact' => 'static_pages#contact'
  match '/signin' => 'static_pages#signin'
  
  match '/orders/search' => 'orders#search'
  match '/customers/search' => 'customers#search'
  match '/customers_addresses/search' => 'customers_addresses#search'
  match '/items/search' => 'items#search'
  match '/items/list' => 'items#list'

  resources :states
  resources :customers
  resources :addresses
  resources :customers_addresses
  resources :orders
  resources :items
  resources :ledgers
  resources :roles
  resources :user_roles
  resources :notes
  resources :payment_types

end

saas/app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id             :integer(3)      not null, primary key
#  name           :string(80)      not null
#  home_phone     :string(20)
#  mobile_phone   :string(20)
#  business_phone :string(20)
#  fax            :string(20)
#  email          :string(80)
#  create_date    :datetime        not null
#  modify_date    :datetime
#  status         :integer(1)      default(1), not null
#

class Customer < ActiveRecord::Base
  self.table_name = 'customers'
  self.primary_key = :id
  self.per_page = 10
  
  attr_accessible :name, :home_phone, :mobile_phone, :business_phone, :fax, :email
  
  has_many :orders

  validates :name, :length => { :maximum => 80 }, :presence => true
  validates :email, :presence => true, :uniqueness => true
  validates_uniqueness_of :home_phone, :allow_nil => true, :allow_blank => true
  validates_uniqueness_of :mobile_phone, :allow_nil => true, :allow_blank => true
    
  def == (other)
    (self.name == other.name) and
    (self.home_phone == other.home_phone or ((self.home_phone.nil? or self.home_phone.empty?) and (other.home_phone.nil? or other.home_phone.empty?))) and
    (self.mobile_phone == other.mobile_phone or ((self.mobile_phone.nil? or self.mobile_phone.empty?) and (other.mobile_phone.nil? or other.mobile_phone.empty?))) and
    (self.business_phone == other.business_phone or ((self.business_phone.nil? or self.business_phone.empty?) and (other.business_phone.nil? or other.business_phone.empty?))) and
    (self.fax == other.fax or ((self.fax.nil? or self.fax.empty?) and (other.fax.nil? or other.fax.empty?))) and
    (self.email == other.email)
  end
  
  def self.not_empty(field)
    return !(field.nil? or field.empty?)
  end
  
  def initialize(attributes=nil, options={})
    super
    self.create_date = Time.new
    self.status = Status::DORMANT
  end
  
  def save
    self.modify_date = Time.new
    self.status = Status::ACTIVE
    super
  end
end

saas/app/controllers/customers_controller.rb
include Status

class CustomersController < ApplicationController
  respond_to :html, :json, :js
  
  def search
    conditions = Hash.new
    
    # Prepare searching conditions
    customer_name = params[:customer_name]
    if !( customer_name.nil? or customer_name.empty? )
      conditions['name LIKE ?'] = customer_name + '%'
    end
      
    home_phone = params[:home_phone]
    if !( home_phone.nil? or home_phone.empty? )
      conditions['home_phone = ?'] = home_phone
    end
    
    mobile_phone = params[:mobile_phone]
    if !( mobile_phone.nil? or mobile_phone.empty? )
      conditions['mobile_phone = ?'] = mobile_phone
    end
    
    business_phone = params[:business_phone]
    if !( business_phone.nil? or business_phone.empty? )
      conditions['business_phone = ?'] = business_phone
    end
        
    email = params[:email]
    if !( email.nil? or email.empty? )
      conditions['email = ?'] = email
    end
    
    # Execute query
    if 0 < conditions.length
      conditions_list = Array.new
      conditions_list << conditions.keys.join(' AND ')
      conditions.values.each {|v| conditions_list << v }
      @customers = Customer.find(:all, :conditions => conditions_list)
    end
    
    # Prepare response
    list = @customers.map { |o| Hash[id: o.id, label: o.name, name: o.name, data: o] }
    respond_to do |format|
      format.json { render json: list }
      format.html # search.html.erb
    end
  end
  
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.page(params[:page]).order(params[:sort])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])
    @status_table = Status.table
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.name.nil? or @customer.name.empty?
        @customer.errors.add(:name, "Please specify customer name")
      end
      
      if !@customer.errors.any?
        if @customer.save
          # Success
          format.html { redirect_to customers_path, notice: 'Customer was successfully created.' }
          format.json { render json: @customer, status: :created, location: @customer }
        else
          # Display error message
          format.html { render action: "new" }
          format.json { render json: @customer.errors, status: :unprocessable_entity }
        end
      else
        # Display error message
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
end

saas/app/helpers/customer_helper.rb
module CustomerHelper
end

saas/app/helpers/customers_helper.rb
module CustomersHelper
  def process(customer)
    if 0 == customer.id.to_i
      # New customer
      customer.save
    else
      # Existing customer, if there is any change to the customer detail,
      # persist the changes
      original_customer = Customer.find(customer.id)
      if original_customer != customer
        customer.save
      end
    end
    
    return customer
  end
  
  module_function :process
end

saas/app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="col" style="width:120px;"><%= f.label :name %></div>
    <div class="col"><%= f.text_field :name %></div>
  </div>
  <div class="field">
    <div class="col" style="width:120px;"><%= f.label :home_phone %></div>
    <div class="col"><%= f.telephone_field :home_phone %></div>
  </div>
  <div class="field">
    <div class="col" style="width:120px;"><%= f.label :mobile_phone %></div>
    <div class="col"><%= f.telephone_field :mobile_phone %></div>
  </div>
  <div class="field">
    <div class="col" style="width:120px;"><%= f.label :business_phone %></div>
    <div class="col"><%= f.telephone_field :business_phone %></div>
  </div>
  <div class="field">
    <div class="col" style="width:120px;"><%= f.label :fax %></div>
    <div class="col"><%= f.telephone_field :fax %></div>
  </div>
  <div class="field">
    <div class="col" style="width:120px;"><%= f.label :email %></div>
    <div class="col"><%= f.text_field :email %></div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

saas/app/views/customers/_info.html.erb
    <%= fields_for :customer, @customer do |customer| %>
    <%= customer.hidden_field :id, :value => @customer.id %>
    <div class="col" style="width:40%">
      <div class="row">
        <div class="col name bold" style="width:30%">NAME</div>
        <div class="col"><%= customer.label @customer.name %></div>
      </div>
      <%= render 'addresses/info' %>
    </div>
    <div class="col"></div>
    <div class="col" style="width:50%">
      <div class="row">
        <div class="col bold" style="width:50%">PHONE</div>
        <div class="col" style="width:40%"><%= number_to_phone(@customer.home_phone, :area_code => true) %></div>
      </div>
      <div class="row">
        <div class="col bold" style="width:50%">MOBILE</div>
        <div class="col" style="width:40%"><%= number_to_phone(@customer.mobile_phone, :area_code => true) %></div>
      </div>
      <div class="row">
        <div class="col bold" style="width:50%">WORK</div>
        <div class="col" style="width:40%"><%= number_to_phone(@customer.business_phone, :area_code => true) %></div>
      </div>
      <div class="row">
        <div class="col bold" style="width:50%">FAX</div>
        <div class="col" style="width:40%"><%= number_to_phone(@customer.fax, :area_code => true) %>
        </div>
      </div>
      <div class="row">
        <div class="col bold" style="width:50%">EMAIL</div>
        <div class="col" style="width:40%"><%= @customer.email %></div>
      </div>
    </div>
    <% end %>

saas/app/views/customers/_order_form.html.erb
  <%= fields_for :customer, @customer do |customer| %>
    <%= customer.hidden_field :id, :value => @customer.id %>
    <div class="col" style="width:40%">
      <div class="row">
        <div class="col name" style="width:30%"><%= customer.label :name, 'NAME' %></div>
        <div class="col"><%= customer.text_field :name,
          :id => 'customer_name' %></div>
      </div>
      <%= render 'addresses/order_form' %>
    </div>
    <div class="col"></div>
    <div class="col" style="width:50%">
      <div class="row">
        <div class="col" style="width:45%"><%= customer.label :home_phone, 'PHONE' %></div>
        <div class="col" style="width:45%">
          <%= customer.telephone_field :home_phone %>
        </div>
      </div>
      <div class="row">
        <div class="col" style="width:45%"><%= customer.label :mobile_phone, 'MOBILE' %></div>
        <div class="col" style="width:45%">
          <%= customer.telephone_field :mobile_phone %>
        </div>
      </div>
      <div class="row">
        <div class="col" style="width:45%"><%= customer.label :business_phone, 'WORK' %></div>
        <div class="col" style="width:45%">
          <%= customer.telephone_field :business_phone %>
        </div>
      </div>
      <div class="row">
        <div class="col" style="width:45%"><%= customer.label :fax, 'FAX' %></div>
        <div class="col" style="width:45%">
          <%= customer.telephone_field :fax %>
        </div>
      </div>
      <div class="row">
        <div class="col" style="width:45%"><%= customer.label :email, 'EMAIL' %></div>
        <div class="col" style="width:45%">
          <%= customer.email_field :email %>
        </div>
      </div>
    </div>
  <% end %>

saas/app/views/customers/_search_form.html.erb
<%= form_tag("/customers/search", :method => "get") do %>
  <div class="row">
    <div class="col"><%= label_tag(:customer_name, "Customer Name:") %></div>
    <div class="col"><%= search_field_tag(:customer_number) %></div>
  </div>
  <%= submit_tag("Search") %>
<% end %>

saas/app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

saas/app/views/customers/index.html.erb
<div class="hero-unit">
  <div class="portlet">
    <div class="left">Customers</div>
    <div class="right link_action">
      <%= link_to "New Customer", new_customer_path %>
    </div>
  </div>
  <div class="row">
    <div class="col bold" style="width:10%">ID</div>
    <div class="col bold" style="width:30%">Name</div>
    <div class="col bold" style="width:30%">Email</div>
    <div class="col bold" style="width:20%">Actions</div>
  </div>
  <% @customers.each do |customer| %>
  <div class="row">
    <div class="col" style="width:10%"><%= customer.id %></div>
    <div class="col" style="width:30%"><%= customer.name %></div>
    <div class="col" style="width:30%"><%= customer.email %></div>
    <div class="col" style="width:20%">
        <%= link_to "Show", customer %>
        <%= link_to "Edit", edit_customer_path(customer) %>
        <%= link_to 'Remove', customer, confirm: 'Are you sure?', method: :delete %>
    </div>
  </div>
  <% end %>
  
  <div class="row">
    <div class="col_r">
      <%= will_paginate @customers %>
    </div>
  </div>
</div>

saas/app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

saas/app/views/customers/search.html.erb
<h1>Customer Search</h1>

<%= render 'search_form' %>

<% if @customers %>
  <% @customers.each do |customer| %>
  <div class="row">
    <div class="col" style="width:20%"><%= customer.id %></div>
    <div class="col" style="width:35%"><%= customer.name %></div>
    <div class="col" style="width:15%"><%= customer.orders.size %></div>
    <div class="col" style="width:20%">
        <%= link_to "Show", customer %>
        &nbsp;
        <%= link_to "Edit", edit_customer_path(customer) %>
    </div>
  </div>
  <% end %>
<% end %>

<%= link_to 'Back', orders_path %>

saas/app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col bold" style="width:20%;">Customer Number:</div>
  <div class="col"><%= @customer.id %></div>
</div>

<div class="row">
  <div class="col bold" style="width:20%;">Name:</div>
  <div class="col"><%= @customer.name %></div>
</div>

<div class="row">
  <div class="col bold" style="width:20%;">Email:</div>
  <div class="col"><%= @customer.email %></div>
</div>

<div class="row">
    <div class="col bold" style="width:20%;">Home Phone:</div>
    <div class="col"><%= @customer.home_phone %></div>
</div>
<div class="row">
    <div class="col bold" style="width:20%;">Business Phone:</div>
    <div class="col"><%= @customer.business_phone %></div>
</div>
<div class="row">
    <div class="col bold" style="width:20%;">Mobile Phone:</div>
    <div class="col"><%= @customer.mobile_phone %></div>
</div>
<div class="row">
    <div class="col bold" style="width:20%;">Fax</div>
    <div class="col"><%= @customer.fax %></div>
</div>

<div class="row">
  <div class="col bold" style="width:20%;">Status:</div>
  <div class="col"><%= @status_table[@customer.status] %></div>
</div>

<div id="orders_list" style="margin-top:20px;">
  <div class="sub_portlet">
    <div class="left">Order History</div>
    <div class="right link_action">
      <%= link_to "New Order", new_order_path(:customer_id => @customer.id) %>
    </div>
  </div>
  <div class="row">
    <div class="col header" style="width:30%">Order Number</div>
    <div class="col header" style="width:40%">Order Date</div>
    <div class="col_r header" style="width:15%">Actions</div>
  </div>
  <% @customer.orders.each do |order| %>
  <div class="row">
    <div class="col" style="width:30%"><%= order.order_number %></div>
    <div class="col" style="width:40%">
        <%= order.order_date.strftime('%m/%d/%Y') %>
    </div>
    <div class="col_r" style="width:15%;">
        <%= link_to "Show", order %>
        <%= link_to "Edit", edit_order_path(order) %>
        <%= link_to 'Remove', order, confirm: 'Are you sure?', method: :delete %>
    </div>
  </div>
  <% end %>
</div>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>