saas/config/routes.rb
Saas::Application.routes.draw do

  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/contact"
  get "static_pages/about"

  match '/home' => 'static_pages#home'
  match '/help' => 'static_pages#help'
  match '/about' => 'static_pages#about'
  match '/contact' => 'static_pages#contact'
  match '/signin' => 'static_pages#signin'
  
  match '/orders/search' => 'orders#search'
  match '/customers/search' => 'customers#search'
  match '/customers_addresses/search' => 'customers_addresses#search'
  match '/items/search' => 'items#search'
  match '/items/list' => 'items#list'

  resources :states
  resources :customers
  resources :addresses
  resources :customers_addresses
  resources :orders
  resources :items
  resources :ledgers
  resources :roles
  resources :user_roles
  resources :notes
  resources :payment_types

end

saas/app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @addresses }
    end
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
    @address = Address.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @address }
    end
  end

  # GET /addresses/new
  # GET /addresses/new.json
  def new
    @address = Address.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @address }
    end
  end

  # GET /addresses/1/edit
  def edit
    @address = Address.find(params[:id])
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(params[:address])

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render json: @address, status: :created, location: @address }
      else
        format.html { render action: "new" }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /addresses/1
  # PUT /addresses/1.json
  def update
    @address = Address.find(params[:id])

    respond_to do |format|
      if @address.update_attributes(params[:address])
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address = Address.find(params[:id])
    @address.destroy

    respond_to do |format|
      format.html { redirect_to addresses_url }
      format.json { head :no_content }
    end
  end
end

saas/app/helpers/addresses_helper.rb
module AddressesHelper
  def process(address, customer)
    if (address.id.nil? or address.id.empty?) and address.save then
      # New address
      # Get the current primary address
      current_primary_address = CustomersAddress.get_primary(customer_id)
      if !current_primary_address.nil? 
        current_primary_address.update_attributes(:is_primary => 0) 
      end
        
      # Save customer address
      ca = CustomersAddress.new
      ca.customer_id = customer_id
      ca.address_id = address.id
      ca.is_primary = 1 # new primary address
      ca.save
    else
      # Existing address; in case there is any changes/updates to the address.
      # Persist new address and change the customer default address
      original_address = Address.find(address.id)
      if original_address != address
        new_address = address.dup
        new_address.save
        address = new_address
          
        # Update customer primary address
        ca = CustomersAddress.get_by_customer_address(customer.id, original_address.id)
        ca.update_attributes(:address_id => address.id)
      end
    end

    return address
  end
  module_function :process
end

saas/app/views/addresses/_form.html.erb
<%= form_for(@address) do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :street1 %><br />
    <%= f.text_field :street1 %>
  </div>
  <div class="field">
    <%= f.label :street2 %><br />
    <%= f.text_field :street2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip_code %><br />
    <%= f.text_field :zip_code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

saas/app/views/addresses/_info.html.erb
      <%= fields_for :address, @address do |address| %>
      <%= address.hidden_field :id, :value => @address.id %>
      <div class="row">
        <div class="col name bold" style="width:30%">ADDRESS</div>
        <div class="col">
          <%= @address.street1 %><br />
          <%= @address.street2 %><br />
          <%= @address.city %>, <%= @address.state %> <%= @address.zip_code %>
        </div>
      </div>
      <% end %>

saas/app/views/addresses/_order_form.html.erb
    <%= fields_for :address, @address do |address| %>
      <%= address.hidden_field :id, :value => @address.id %>
      <div class="row">
        <div class="col name" style="width:30%"><%= address.label :street1, 'ADDRESS' %></div>
        <div class="col">
          <%= address.text_field :street1,
            :value => (@address.is_empty(@address.street1) ? 'street 1' : @address.street1) %><br />
          <%= address.text_field :street2,
            :value => (@address.is_empty(@address.street2) ? (@address.is_empty(@address.street1) ? 'street 2' : '') : @address.street2) %><br />
          <%= address.text_field :city,
            :value => (@address.is_empty(@address.city) ? (@address.is_empty(@address.street1) ? 'city' : '') : @address.city) %><br />
          <%= address.collection_select(:state, 
            @state_list, 
            :abbreviation, 
            :abbreviation, 
            { :prompt => 'state...' } ) %><br />
          <%= address.text_field :zip_code,
            :value => (@address.is_empty(@address.zip_code) ? (@address.is_empty(@address.street1) ? 'zip code' : '') : @address.zip_code) %>
        </div>
      </div>
    <% end %>

saas/app/views/addresses/edit.html.erb
<h1>Editing address</h1>

<%= render 'form' %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

saas/app/views/addresses/index.html.erb
<h1>Listing addresses</h1>

<table>
  <tr>
    <th>Street1</th>
    <th>Street2</th>
    <th>City</th>
    <th>State</th>
    <th>Zip code</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @addresses.each do |address| %>
  <tr>
    <td><%= address.street1 %></td>
    <td><%= address.street2 %></td>
    <td><%= address.city %></td>
    <td><%= address.state %></td>
    <td><%= address.zip_code %></td>
    <td><%= address.status %></td>
    <td><%= link_to 'Show', address %></td>
    <td><%= link_to 'Edit', edit_address_path(address) %></td>
    <td><%= link_to 'Destroy', address, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Address', new_address_path %>

saas/app/views/addresses/new.html.erb
<h1>New address</h1>

<%= render 'form' %>

<%= link_to 'Back', addresses_path %>

saas/app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Street1:</b>
  <%= @address.street1 %>
</p>

<p>
  <b>Street2:</b>
  <%= @address.street2 %>
</p>

<p>
  <b>City:</b>
  <%= @address.city %>
</p>

<p>
  <b>State:</b>
  <%= @address.state %>
</p>

<p>
  <b>Zip code:</b>
  <%= @address.zip_code %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>