saas/config/routes.rb
Saas::Application.routes.draw do

  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/contact"
  get "static_pages/about"

  match '/home' => 'static_pages#home'
  match '/help' => 'static_pages#help'
  match '/about' => 'static_pages#about'
  match '/contact' => 'static_pages#contact'
  match '/signin' => 'static_pages#signin'
  
  match '/orders/search' => 'orders#search'
  match '/customers/search' => 'customers#search'
  match '/customers_addresses/search' => 'customers_addresses#search'
  match '/items/search' => 'items#search'
  match '/items/list' => 'items#list'

  resources :states
  resources :customers
  resources :addresses
  resources :customers_addresses
  resources :orders
  resources :items
  resources :ledgers
  resources :roles
  resources :user_roles
  resources :notes
  resources :payment_types

end

saas/app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id              :string(128)     not null, primary key
#  order_number    :string(10)      not null
#  customer_id     :integer(3)      not null
#  lead_source     :string(255)
#  delivery_option :string(80)
#  price           :float
#  finishing_cost  :float
#  delivery_charge :float
#  sales_tax       :float
#  payment_method  :string(20)
#  deposit         :float
#  balance         :float
#  order_date      :datetime        not null
#  due_date        :date
#  delivery_date   :date
#  status          :integer(1)      default(1), not null
#

require 'uuid'
require 'store.rb'

class Order < ActiveRecord::Base
  include Status
  
  self.table_name = 'orders'
  self.primary_key = :id
  self.per_page = 10
    
  attr_accessible :branch, :order_number, :customer_id, :address_id, :lead_source, 
    :price, :discount, :sales_tax, :finishing, 
    :delivery_option, :delivery_charge, 
    :order_date, :estimated_time, :delivery_date
   
  belongs_to :customer, :primary_key => 'id', :foreign_key => 'customer_id'
  has_one :address, :primary_key => 'address_id', :foreign_key => 'id'
  has_many :items, :primary_key => 'order_number', :foreign_key => 'order_number', :conditions => "status IN (1,2,8,16)", :order => :item_number
  has_many :ledgers, :primary_key => 'order_number', :foreign_key => 'order_number', :conditions => "status IN (1,2,8,16)", :order => :payment_date
  has_many :notes, :primary_key => 'order_number', :foreign_key => 'order_number', :conditions => "status IN (1,2,8,16)", :order => :create_date
  
  validates_presence_of :order_number, :customer_id, :address_id, :price, :sales_tax, :delivery_option, :estimated_time

  attr_accessor :branch, :balance
  
  def == (other)
    (self.order_number == other.order_number) and
    (self.customer_id == other.customer_id) and
    (self.address_id == other.address_id) and
    (self.lead_source == other.lead_source or ((self.lead_source.nil? or self.lead_source.empty?) and (other.lead_source.nil? or other.lead_source.empty?))) and
    (self.estimated_time == other.estimated_time) and
    (self.delivery_option == other.delivery_option) and
    (self.price == other.price) and
    (self.sales_tax == other.sales_tax) and
    (self.finishing == other.finishing) and
    (self.delivery_charge == other.delivery_charge) and
    (self.delivery_date == other.delivery_date or ((self.delivery_date.nil? or self.delivery_date.empty?) and (other.delivery_date.nil? or other.delivery_date.empty?)))
  end
  
  def initialize(attributes=nil, options={})
    super
    self.order_date = Time.new
    self.status = Status::DORMANT
  end
  
  def save
    uuid = UUID.new
    self.id = uuid.generate
    self.modify_date = Time.new
    
    if self.order_number.nil? or 'NEW ORDER' == self.order_number
      self.order_number = Store.next_order_number(self.branch)
    end
    
    super
  end
  
  def status_description
    Status.description(self.status)
  end
  
  def label
    self.order_number
  end
  
  def name
    self.order_number
  end
  
  def subtotal
    self.price.to_f + self.sales_tax.to_f
  end
  
  def total
    self.subtotal + self.finishing.to_f + self.delivery_charge.to_f
  end

  def remaining_balance
    result = self.total  
    self.ledgers.each {|l| result -= l.amount}
    return result  
  end
  
  # Get by order number
  def self.by_order_number(order_number)
    Order.find_executable(:all, :conditions => ['order_number = ?  AND status <> ?', order_number, Status::INACTIVE]).first
  end
end

saas/app/controllers/orders_controller.rb
include DeliveryOptions
include LeadSources
include Status

class OrdersController < ApplicationController
  respond_to :html, :json, :js
  before_filter :options, :only => [:new, :create, :edit, :update]
  
  # GET /search
  def search
    # Support multiple search criteria
    conditions = Hash.new
    
    # By order number
    order_number = params[:order_number]
    if order_number
      conditions['order_number LIKE ?'] = order_number + '%'
    end

    # By order date
    order_date = params[:order_date]
    if order_number.empty? and order_date
      order_date = Date.strptime(params[:order_date], "%m/%d/%Y")
      conditions['order_date LIKE ?'] = order_date.strftime('%Y-%m-%d ') + '%'
    end
    
    # By customer ID
    customer_id = params[:customer_id]
    if 0 < customer_id.to_i
      conditions['customer_id = ?'] = customer_id.to_i
    end
    
    # If there is any search criteria specified, performs a search
    if ! conditions.empty?
      conditions['status <> ?'] = Status::INACTIVE
        
      conditions_list = Array.new
      conditions_list << conditions.keys.join(' AND ')
      conditions.values.each {|v| conditions_list << v }  
      @orders = Order.find(:all, :conditions => conditions_list, :order => 'order_number ASC')
    end
    
    # Output
    list = @orders.map {|o| Hash[id: o.order_number, label: o.order_number, name: o.order_number, data: o]}
    respond_to do |format|
      format.json { render json: list }
      format.html # search.html.erb
    end
  end
  
  # GET /orders
  # GET /orders.json
  def index
    # params[:sort]
    status_condition = 'status <> ' + Status::INACTIVE.to_s
    @orders = Order.where(status_condition).page(params[:page]).order(:order_number)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])
    @customer = @order.customer
    @address = @order.address
    @items = @order.items
    @ledgers = @order.ledgers
    @notes = @order.notes

    # Remaining balance
    @remaining_balance = @order.remaining_balance

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  def is_sketchup
    OrdersHelper.browser_type(request, 'SketchUp')
  end
  
  # GET /orders/new
  # GET /orders/new.json
  def new
    @item = Item.new
    
    @order = Order.new
    @order.order_number = 'NEW ORDER'
    
    @customer = Customer.new
    @address = Address.new
    @address.state = 'IL'
    
    # Ledgers
    @deposit_ledger = Ledger.new
    @payment_ledger = Ledger.new
    
    # Remaining balance
    @remaining_balance = 'NEW ORDER'
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
    @customer = @order.customer
    @address = @order.address
    @items = @order.items
    @ledgers = @order.ledgers
    @notes = @order.notes
    
    @item = Item.new(order_number: @order.order_number)
    @ledger = Ledger.new(order_number: @order.order_number)
    @note = Note.new(order_number: @order.order_number)
    
    # Remaining balance
    @remaining_balance = @order.remaining_balance
  end

  # POST /orders
  # POST /orders.json
  def create
    respond_to do |format|
      result = OrdersHelper.process_order(request, params)
      @order = result[0]
      @customer = result[1]
      @address = result[2]
      @item = result[3]
      
      if !(@order.errors.any? or @customer.errors.any? or @address.errors.any? or @item.errors.any?) then
        format.json { render json: @item }
        format.html { redirect_to @order }
      else
        # Display error message
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end    
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    respond_to do |format|
      result = OrdersHelper.process_order(request, params)
      @order = result[0]
      @customer = result[1]
      @address = result[2]
      @item = result[3]

      if !(@order.errors.any? or @customer.errors.any? or @address.errors.any? or @item.errors.any?) then
        format.json { render json: @item }
        format.html { redirect_to @order }
      else
        # Display error message
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
  
  protected
    def options
      # Options for select box
      @state_list = State.order(:name)
      @delivery_option_list = DeliveryOptions.table
      @estimated_time_list = EstimatedCompletionTime.table
      @lead_source_list = LeadSources.table
      @payment_type_list = PaymentType.order(:name)
      @payment_method_list = PaymentMethods.table
      @status_list = Status.table
    end
end

saas/app/helpers/orders_helper.rb
module OrdersHelper
  def lead_source
    'How did you hear about us?'
  end
  
  def browser_type(request, type)
    browser = request.env['HTTP_USER_AGENT']
    matches = /#{type}/.match(browser)
    return (matches.nil? ? false : type == matches[0])
  end

  def is_sketchup?
    OrdersHelper.browser_type(request, 'SketchUp')
  end

  def process_order(request, params)
    # Item image file
    item_file_fields = (params.has_key?(:image_file) ? params[:image_file] : nil)
    temp_image_file = (item_file_fields.nil? ? nil : item_file_fields.tempfile)
    
    # Parameters
    store = (params.has_key?(:store) ? params[:store] : nil)
    if store.nil? or store.empty?
      store = 'HALSTED'
    end
         
    item = Item.new(params[:item])
      
    order = Order.new(params[:order])
    order.id = params[:order][:id]
    order.branch = store
        
    customer = Customer.new(params[:customer])
    customer.id = params[:customer][:id]
    order.customer_id = customer.id.to_i
      
    address = Address.new(params[:address])
    address.id = params[:address][:id]
    order.address_id = address.id

    # Customer
    customer = CustomersHelper.process(customer)
      
    # Address
    if !(customer.errors.any?)
      # Process order address information
      address = AddressesHelper.process(address, customer)
    end

    # Order
    if !(customer.errors.any? or address.errors.any?) then
      # Assign order address ID
      order.address_id = address.id

      # Assign order customer ID
      order.customer_id = customer.id
      
      # Process the order
      order = OrdersHelper.process(order)
    end

    # Item    
    if !(item.quantity.nil? or order.errors.any? or customer.errors.any? or address.errors.any?) then
      # Assign item order number
      item.order_number = order.order_number

      # Process new item
      item = ItemsHelper.process(item, temp_image_file)
    end
    
    return [order, customer, address, item]
  end
  
  def process(order)
    if order.id.nil? or order.id.empty?
      # Persist new order
      order.save
    else 
      # Existing order
      original_order = Order.find(order.id)
      if original_order != order
        # Save order history
        new_order = order.dup
        new_order.order_date = original_order.order_date
        new_order.save
        order = new_order
        
        original_order.status = Status::INACTIVE
        original_order.save!
      end
    end
    
    return order
  end
  
  module_function :browser_type, :process_order, :process
end

saas/app/views/orders/_form.html.erb
<%= form_for @order, :html => { :multipart => true}, :remote => @order.new_record? do |order| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this adderss from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="order_form_tabs">
    <ul>
      <li><a href="#order_detail">Detail</a></li>
      <li><a href="#order_charge">Price</a></li>
      <li><a href="#order_payment">Payment</a></li>
      <li><a href="#order_note">Note</a></li>
    </ul>

    <div id="order_detail" class="row" style="padding-left:50px">
      <div id="order_info" class="row">
        <%= render 'orders/order_form' %>
      </div>
    
      <div id="customer_detail" class="row">
        <%= render 'customers/order_form' %>
      </div>
      
      <div id="items" class="row" style="margin-top:20px">
        <%= render 'items/order_form' %>
      </div>
    </div>
      
    <div id="order_charge" class="row" style="margin-left:30%">
      <%= render 'orders/price_form' %>
    </div>
    <div id="order_payment" class="row" style="padding-left:60px">
      <% if @ledgers %>
        <%= render 'ledgers/ledger_dialog' %>
        <div id="ledgers_list_form">
          <%= render 'ledgers/list_form' %>
        </div>
      <% end %>
    </div>
    <div id="order_note" class="row" style="padding-left:60px">
      <% if @notes %>
        <%= render 'notes/note_dialog' %>
        <div id="notes_list_form">
          <%= render 'notes/list_form' %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row"></div>
  <div class="row" style="padding-top:20px;">
    <div class="col_r">
      <%= button_tag "Submit",
        :id => "submit_button",
        :name => "submit_button",
        :type => "submit" 
      %>
    </div>
  </div>
<% end %>
  

saas/app/views/orders/_header.html.erb
<center>
<h2>Store Name</h2>
<h3>Store Mailing Address</h3>
<h4>Store Website Address</h4>
<br />
<h2>ORDER FORM</h2>
</center>

saas/app/views/orders/_info.html.erb
    <%= fields_for :order, @order do |order| %>
    <%= order.hidden_field :id, :value => @order.id %>
    <div class="col" style="width:40%">
      <div class="row">
        <div class="col name bold" style="width:30%">DATE</div>
        <div class="col"><%= order.label @order.order_date.strftime('%m/%d/%Y') %></div>
      </div>
      <div class="row">
        <div class="col name bold" style="width:30%">ORDER#</div>
        <div class="col"><%= order.label @order.order_number %></div>
      </div>
    </div>
    <div class="col"></div>
    <div class="col" style="width:50%">
      <div class="row">
        <div class="col bold" style="width:50%">Estimated Completion Time</div>
        <div class="col" style="width:40%"><%= order.label @order.estimated_time.to_s + ' Weeks' %></div>
      </div>
      <div class="row">
        <div class="col bold" style="width:50%">DELIVERY OPTION</div>
        <div class="col" style="width:40%"><%= order.label @order.delivery_option %></div>
      </div>
    </div>
    <% end %>

saas/app/views/orders/_info_header.html.erb
<center>
<h2>Store Name</h2>
<h3>Store Mailing Address</h3>
<h4>Store Website Address</h4>
<br />
<h2>ORDER DETAIL</h2>
</center>

saas/app/views/orders/_info_price.html.erb
    <%= fields_for :order, @order do |order| %>
      <div class="row">
        <div class="col name bold" style="width:30%">Price w/o finish</div>
        <div class="col right_text" style="width:35%"><%= number_to_currency(@order.price) %></div>
      </div>
      <div class="row">
        <div class="col name bold" style="width:30%">Tax</div>
        <div class="col right_text" style="width:35%"><%= number_to_currency(@order.sales_tax) %></div>
      </div>
      <div class="row" style="width:65%"><hr /></div>     
      <div class="row">
        <div class="col name bold" style="width:30%">Subtotal</div>
        <div class="col right_text" style="width:35%"><%= number_to_currency(@order.subtotal) %></div>
      </div>
      <div class="row" style="width:65%"><hr /></div>     
      <div class="row">
        <div class="col name bold" style="width:30%">Finishing</div>
        <div class="col right_text" style="width:35%"><%= number_to_currency(@order.finishing) %></div>
      </div>
      <div class="row">
        <div class="col name bold" style="width:30%">Delivery Charge</div>
        <div class="col right_text" style="width:35%"><%= number_to_currency(@order.delivery_charge) %></div>
      </div>
      <div class="row" style="width:65%"><hr /></div>     
      <div class="row">
        <div class="col name bold" style="width:30%">Total</div>
        <div class="col right_text" style="width:35%"><%= number_to_currency(@order.total) %></div>
      </div>
    <% end %>

saas/app/views/orders/_list.html.erb
<h1>New Order</h1>
<%= fields_for(@order) do |order| %>
<%= render 'orders/form', :f => order %>
<% end %>

saas/app/views/orders/_new.html.erb
<h1>New Order</h1>
<%= fields_for(@order) do |order| %>
<%= render 'orders/form', :f => order %>
<% end %>

saas/app/views/orders/_order_form.html.erb
    <%= fields_for :order, @order do |order| %>
    <%= order.hidden_field :id, :value => @order.id %>
    <div class="col" style="width:40%">
      <div class="row">
        <div class="col name" style="width:30%"><%= order.label :order_date, 'DATE' %></div>
        <div class="col"><%= order.text_field :order_date, 
          :id => 'order_date',
          :value => @order.order_date.strftime('%m/%d/%Y'),
          :readonly => 'true' %></div>
      </div>
      <div class="row">
        <div class="col name" style="width:30%"><%= order.label :order_number, 'ORDER#' %></div>
        <div class="col note" title="If this is a new order, leave 'NEW ORDER' intact">
          <%= order.text_field :order_number,
            :id => 'order_number' %>
        </div>
      </div>
    </div>
    <div class="col"></div>
    <div class="col" style="width:50%">
      <div class="row">
        <div class="col" style="width:45%"><%= order.label :estimated_time, 'Estimated Completion Time' %></div>
        <div class="col" style="width:45%">
          <%= order.collection_select(:estimated_time, 
            @estimated_time_list, 
            :key, 
            :option, 
            { :prompt => 'select...' } ) %>
        </div>
      </div>
      <div class="row">
        <div class="col" style="width:45%"><%= order.label :delivery_option, 'DELIVERY OPTION' %></div>
        <div class="col" style="width:45%">
          <%= order.collection_select(:delivery_option, 
            @delivery_option_list, 
            :key, 
            :option, 
            { :prompt => 'select...' } ) %>
        </div>
      </div>
    </div>
    <% end %>

saas/app/views/orders/_price_form.html.erb
    <%= fields_for :order, @order do |order| %>
      <div class="row">
        <div class="col name" style="width:30%">
          <%= order.label :price, 'Price w/o finish' %></div>
        <div class="col">&#36;<%= order.text_field :price,
          :class => 'custom_text short right_text',
          :onchange => 'Order.update_tax_and_subtotal();' %></div>
      </div>
      <div class="row">
        <div class="col name" style="width:30%">
          <%= order.label :sales_tax, 'Tax' %></div>
        <div class="col">&#36;<%= order.text_field :sales_tax,
          :class => 'custom_text short right_text' %></div>
      </div>
      <div class="row">
        <div class="col name" style="width:30%">
          <%= order.label :subtotal, 'Subtotal' %></div>
        <div class="col">&#36;<%= text_field_tag :order_subtotal, @order.subtotal,
          :class => 'custom_text short right_text',
          :onchange => 'Order.adjust_subtotal();' %></div>
      </div>
      <div class="row">
        <div class="col name" style="width:30%">
          <%= order.label :finishing, 'Finishing' %></div>
        <div class="col">&#36;<%= order.text_field :finishing,
          :id => 'order_finishing',
          :class => 'custom_text short right_text',
          :onchange => 'Order.update_total();' %></div>
      </div>
      <div class="row">
        <div class="col name" style="width:30%">
          <%= order.label :pickup_charge, 'Delivery Charge' %></div>
        <div class="col">&#36;<%= order.text_field :delivery_charge,
          :class => 'custom_text short right_text',
          :onchange => 'Order.update_total();' %></div>
      </div>
      <div class="row">
        <div class="col name" style="width:30%">
          <%= order.label 'Total' %></div>
        <div class="col">&#36;<%= text_field_tag :order_total, @order.total,
          :class => 'custom_text short right_text',
          :onchange => 'Order.adjust_total();' %></div>
      </div>
    <% end %>

saas/app/views/orders/_search_form.html.erb
<%= form_tag("/orders/search", :method => "get") do %>
  <div class="row">
    <div class="col"><%= label_tag(:order_number, "Order Number:") %></div>
    <div class="col"><%= search_field_tag(:order_number) %></div>
  </div>
  <%= submit_tag("Search") %>
<% end %>

saas/app/views/orders/edit.html.erb
<h1><span class="edit_title">Editing Order</span> :: <%= @order.order_number %></h1>
<%= render 'header' %>
<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

saas/app/views/orders/index.html.erb
<div class="hero-unit">
  <div class="portlet">
    <div class="left">Orders</div>
    <div class="right link_action">
      <%= link_to "New Order", new_order_path %>
    </div>
  </div>
  <div class="row">
    <div class="col bold" style="width:15%">Order Number</div>
    <div class="col bold" style="width:20%">Customer</div>
    <div class="col bold" style="width:10%"># of Items</div>
    <div class="col bold" style="width:10%">Price</div>
    <div class="col bold" style="width:20%">Status</div>
    <div class="col bold" style="width:15%">Actions</div>
  </div>
  <% @orders.each do |order| %>
  <div class="row">
    <div class="col" style="width:15%"><%= order.order_number %></div>
    <div class="col" style="width:20%"><%= order.customer.name %></div>
    <div class="col" style="width:10%"><%= order.items.size %></div>
    <div class="col" style="width:10%"><%= order.price %></div>
    <div class="col" style="width:20%"><%= order.status_description %></div>
    <div class="col" style="width:15%">
        <%= link_to "Show", order %>
        &nbsp;
        <%= link_to "Edit", edit_order_path(order) %>
    </div>
  </div>
  <% end %>
  
  <div class="row">
    <div class="col_r">
      <%= will_paginate @orders %>
    </div>
  </div>
</div>

saas/app/views/orders/new.html.erb
<%= render 'header' %>
<%= render 'form' %>  

<%= link_to 'Back', items_path %>

saas/app/views/orders/search.html.erb
<h1>Order Search</h1>

<%= render 'search_form' %>

<% if @orders %>
  <% @orders.each do |order| %>
  <div class="row">
    <div class="col" style="width:20%"><%= order.order_number %></div>
    <div class="col" style="width:20%"><%= order.customer.name %></div>
    <div class="col" style="width:15%"><%= order.price %></div>
    <div class="col" style="width:15%"><%= order.items.size %></div>
    <div class="col" style="width:20%">
        <%= link_to "Show", order %>
        &nbsp;
        <%= link_to "Edit", edit_order_path(order) %>
    </div>
  </div>
  <% end %>
<% end %>

<%= link_to 'Back', orders_path %>